name: Deploy Convex Functions

on:
  push:
    branches:
      - main
    paths:
      - 'convex/**'
      - '.github/workflows/deploy-convex.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install
          npm install -g convex

      - name: Deploy Convex
        env:
          CONVEX_DEPLOYMENT: ${{ secrets.CONVEX_URL }}
          CONVEX_ADMIN_KEY: ${{ secrets.CONVEX_ADMIN_KEY }}
        run: |
          echo '{"project": "default"}' > convex.json
          npx convex deploy
