name: Deploy Convex Functions

on:
  push:
    branches:
      - main
    paths:
      - 'convex/**'
      - '.github/workflows/deploy-convex.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install
          npm install -g convex

      - name: Deploy Convex
        env:
          CONVEX_URL: ${{ secrets.CONVEX_URL }}
          CONVEX_ADMIN_KEY: ${{ secrets.CONVEX_ADMIN_KEY }}
          NODE_TLS_REJECT_UNAUTHORIZED: '0' # Only if you're having SSL issues
        run: |
          # Create convex config for self-hosted instance
          echo '{
            "project": "default",
            "team": "team",
            "deploymentUrl": "${{ secrets.CONVEX_URL }}",
            "adminKey": "${{ secrets.CONVEX_ADMIN_KEY }}"
          }' > convex.json
          
          # Deploy to self-hosted instance
          npx convex deploy --url ${{ secrets.CONVEX_URL }} --admin-key ${{ secrets.CONVEX_ADMIN_KEY }}
